//! Platform-neutral input events delivered to the app and to tabs.

/// Editing intents. On macOS these come from the Cocoa key-binding system
/// (`doCommandBySelector:`), so user-customised bindings keep working.
pub const EditCommand = enum {
    move_left,
    move_right,
    move_word_left,
    move_word_right,
    move_line_start,
    move_line_end,
    move_up,
    move_down,
    move_doc_start,
    move_doc_end,
    select_left,
    select_right,
    select_word_left,
    select_word_right,
    select_line_start,
    select_line_end,
    select_up,
    select_down,
    select_doc_start,
    select_doc_end,
    select_all,
    delete_backward,
    delete_forward,
    delete_word_backward,
    delete_word_forward,
    delete_to_line_start,
    delete_to_line_end,
    insert_newline,
    insert_line_break,
    insert_tab,
    insert_backtab,
    cancel,
    page_up,
    page_down,
    scroll_to_top,
    scroll_to_bottom,
};

const Mapping = struct { sel: []const u8, cmd: EditCommand };

/// Cocoa selector name → EditCommand.
pub const selector_map = [_]Mapping{
    .{ .sel = "moveLeft:", .cmd = .move_left },
    .{ .sel = "moveBackward:", .cmd = .move_left },
    .{ .sel = "moveRight:", .cmd = .move_right },
    .{ .sel = "moveForward:", .cmd = .move_right },
    .{ .sel = "moveWordLeft:", .cmd = .move_word_left },
    .{ .sel = "moveWordBackward:", .cmd = .move_word_left },
    .{ .sel = "moveWordRight:", .cmd = .move_word_right },
    .{ .sel = "moveWordForward:", .cmd = .move_word_right },
    .{ .sel = "moveToBeginningOfLine:", .cmd = .move_line_start },
    .{ .sel = "moveToLeftEndOfLine:", .cmd = .move_line_start },
    .{ .sel = "moveToBeginningOfParagraph:", .cmd = .move_line_start },
    .{ .sel = "moveToEndOfLine:", .cmd = .move_line_end },
    .{ .sel = "moveToRightEndOfLine:", .cmd = .move_line_end },
    .{ .sel = "moveToEndOfParagraph:", .cmd = .move_line_end },
    .{ .sel = "moveUp:", .cmd = .move_up },
    .{ .sel = "moveDown:", .cmd = .move_down },
    .{ .sel = "moveToBeginningOfDocument:", .cmd = .move_doc_start },
    .{ .sel = "moveToEndOfDocument:", .cmd = .move_doc_end },
    .{ .sel = "moveLeftAndModifySelection:", .cmd = .select_left },
    .{ .sel = "moveBackwardAndModifySelection:", .cmd = .select_left },
    .{ .sel = "moveRightAndModifySelection:", .cmd = .select_right },
    .{ .sel = "moveForwardAndModifySelection:", .cmd = .select_right },
    .{ .sel = "moveWordLeftAndModifySelection:", .cmd = .select_word_left },
    .{ .sel = "moveWordBackwardAndModifySelection:", .cmd = .select_word_left },
    .{ .sel = "moveWordRightAndModifySelection:", .cmd = .select_word_right },
    .{ .sel = "moveWordForwardAndModifySelection:", .cmd = .select_word_right },
    .{ .sel = "moveToBeginningOfLineAndModifySelection:", .cmd = .select_line_start },
    .{ .sel = "moveToLeftEndOfLineAndModifySelection:", .cmd = .select_line_start },
    .{ .sel = "moveToBeginningOfParagraphAndModifySelection:", .cmd = .select_line_start },
    .{ .sel = "moveToEndOfLineAndModifySelection:", .cmd = .select_line_end },
    .{ .sel = "moveToRightEndOfLineAndModifySelection:", .cmd = .select_line_end },
    .{ .sel = "moveToEndOfParagraphAndModifySelection:", .cmd = .select_line_end },
    .{ .sel = "moveUpAndModifySelection:", .cmd = .select_up },
    .{ .sel = "moveDownAndModifySelection:", .cmd = .select_down },
    .{ .sel = "moveToBeginningOfDocumentAndModifySelection:", .cmd = .select_doc_start },
    .{ .sel = "moveToEndOfDocumentAndModifySelection:", .cmd = .select_doc_end },
    .{ .sel = "selectAll:", .cmd = .select_all },
    .{ .sel = "deleteBackward:", .cmd = .delete_backward },
    .{ .sel = "deleteBackwardByDecomposingPreviousCharacter:", .cmd = .delete_backward },
    .{ .sel = "deleteForward:", .cmd = .delete_forward },
    .{ .sel = "deleteWordBackward:", .cmd = .delete_word_backward },
    .{ .sel = "deleteWordForward:", .cmd = .delete_word_forward },
    .{ .sel = "deleteToBeginningOfLine:", .cmd = .delete_to_line_start },
    .{ .sel = "deleteToBeginningOfParagraph:", .cmd = .delete_to_line_start },
    .{ .sel = "deleteToEndOfLine:", .cmd = .delete_to_line_end },
    .{ .sel = "deleteToEndOfParagraph:", .cmd = .delete_to_line_end },
    .{ .sel = "insertNewline:", .cmd = .insert_newline },
    .{ .sel = "insertLineBreak:", .cmd = .insert_line_break },
    .{ .sel = "insertNewlineIgnoringFieldEditor:", .cmd = .insert_line_break },
    .{ .sel = "insertTab:", .cmd = .insert_tab },
    .{ .sel = "insertBacktab:", .cmd = .insert_backtab },
    .{ .sel = "cancelOperation:", .cmd = .cancel },
    .{ .sel = "pageUp:", .cmd = .page_up },
    .{ .sel = "scrollPageUp:", .cmd = .page_up },
    .{ .sel = "pageDown:", .cmd = .page_down },
    .{ .sel = "scrollPageDown:", .cmd = .page_down },
    .{ .sel = "scrollToBeginningOfDocument:", .cmd = .scroll_to_top },
    .{ .sel = "scrollToEndOfDocument:", .cmd = .scroll_to_bottom },
};

pub fn commandForSelector(name: []const u8) ?EditCommand {
    const std = @import("std");
    for (selector_map) |m| {
        if (std.mem.eql(u8, m.sel, name)) return m.cmd;
    }
    return null;
}
